// <auto-generated />
using System;
using ApiSistemaEstoque.ApiSistemaEstoque.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiSistemaEstoque.Infrastructure.Migrations
{
    [DbContext(typeof(EstoqueContext))]
    [Migration("20260115144740_CorrigirItemEstoquePK")]
    partial class CorrigirItemEstoquePK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Inativo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Superior")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("Superior");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Estoque", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Inativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Superior")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.HistoricoValorItem", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoProduto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicial")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Codigo");

                    b.ToTable("HistoricoValorItens");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoUnidade")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Inativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeMinima")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCategoria");

                    b.HasIndex("CodigoUnidade");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.ItemEstoque", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoItem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstoqueCodigo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoEstoque");

                    b.HasIndex("EstoqueCodigo");

                    b.HasIndex("CodigoItem", "CodigoEstoque")
                        .IsUnique();

                    b.ToTable("ItensEstoque");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.ItemMovimentacao", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoMovimentacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoMovimentacao");

                    b.ToTable("ItensMovimentacao");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.KardexDiario", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoEstoqueDestino")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoEstoqueOrigem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoItem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoMovimentacao")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeEstoqueDestinoFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeEstoqueDestinoInicial")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeEstoqueOrigemFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeEstoqueOrigemInicial")
                        .HasColumnType("INTEGER");

                    b.HasKey("Codigo");

                    b.ToTable("KardexDiario");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Movimentacao", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoEstoqueSolicitado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoEstoqueSolicitante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoTipoMovimentacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoUsuarioEstoqueSolicitado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoUsuarioEstoqueSolicitante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Novo");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoTipoMovimentacao");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.TipoMovimentacao", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Inativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("TiposMovimentacoes");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Unidade", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Inativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Categoria", null)
                        .WithMany()
                        .HasForeignKey("Superior")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Item", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CodigoCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("CodigoUnidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.ItemEstoque", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Estoque", "Estoque")
                        .WithMany()
                        .HasForeignKey("CodigoEstoque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("CodigoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Estoque", null)
                        .WithMany("ItensEstoque")
                        .HasForeignKey("EstoqueCodigo");

                    b.Navigation("Estoque");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.ItemMovimentacao", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Movimentacao", "Movimentacao")
                        .WithMany("ItensMovimentacao")
                        .HasForeignKey("CodigoMovimentacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Movimentacao", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.TipoMovimentacao", "TipoMovimentacao")
                        .WithMany()
                        .HasForeignKey("CodigoTipoMovimentacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoMovimentacao");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Estoque", b =>
                {
                    b.Navigation("ItensEstoque");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Movimentacao", b =>
                {
                    b.Navigation("ItensMovimentacao");
                });
#pragma warning restore 612, 618
        }
    }
}
