// <auto-generated />
using System;
using ApiSistemaEstoque.ApiSistemaEstoque.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiSistemaEstoque.Migrations
{
    [DbContext(typeof(EstoqueContext))]
    [Migration("20250107143401_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Superior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioCadastro")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Estoque", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Responsavel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Superior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioCadastro")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.HistoricoValorItem", b =>
                {
                    b.Property<int?>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoProduto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicial")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Codigo");

                    b.ToTable("HistoricoValorItens");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoUnidade")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeMinima")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioCadastro")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCategoria");

                    b.HasIndex("CodigoUnidade");

                    b.HasIndex("UsuarioCadastro");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.ItemEstoque", b =>
                {
                    b.Property<int?>("CodigoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("CodigoEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstoqueCodigo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Quantidade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("CodigoItem", "CodigoEstoque");

                    b.HasIndex("CodigoEstoque");

                    b.HasIndex("EstoqueCodigo");

                    b.ToTable("ItensEstoque");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.ItemMovimentacao", b =>
                {
                    b.Property<int?>("CodigoMovimentacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("Item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("CodigoMovimentacao", "Item");

                    b.ToTable("ItensMovimentacao");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.KardexDiario", b =>
                {
                    b.Property<int?>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoEstoqueDestino")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoEstoqueOrigem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoItem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoMovimentacao")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeEstoqueDestinoFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeEstoqueDestinoInicial")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeEstoqueOrigemFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeEstoqueOrigemInicial")
                        .HasColumnType("INTEGER");

                    b.HasKey("Codigo");

                    b.ToTable("KardexDiario");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Movimentacao", b =>
                {
                    b.Property<int?>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoEstoqueSolicitado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoEstoqueSolicitante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoTipoMovimentacao")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoUsuarioEstoqueSolicitado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoUsuarioEstoqueSolicitante")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Aguardando");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoTipoMovimentacao");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Setor", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Inativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioCadastro")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Setor");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.TipoMovimentacao", b =>
                {
                    b.Property<int?>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioCadastro")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("TiposMovimentacoes");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Unidade", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioCadastro")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoSetor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioCadastro")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoSetor");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Item", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CodigoCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("CodigoUnidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioCadastro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Unidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.ItemEstoque", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Estoque", "Estoque")
                        .WithMany()
                        .HasForeignKey("CodigoEstoque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("CodigoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Estoque", null)
                        .WithMany("ItensEstoque")
                        .HasForeignKey("EstoqueCodigo");

                    b.Navigation("Estoque");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.ItemMovimentacao", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Movimentacao", "Movimentacao")
                        .WithMany("ItensMovimentacao")
                        .HasForeignKey("CodigoMovimentacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Movimentacao", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.TipoMovimentacao", "TipoMovimentacao")
                        .WithMany()
                        .HasForeignKey("CodigoTipoMovimentacao")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoMovimentacao");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Setor", "Setor")
                        .WithMany("Usuarios")
                        .HasForeignKey("CodigoSetor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Estoque", b =>
                {
                    b.Navigation("ItensEstoque");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Movimentacao", b =>
                {
                    b.Navigation("ItensMovimentacao");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Setor", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
