// <auto-generated />
using System;
using ApiSistemaEstoque.ApiSistemaEstoque.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiSistemaEstoque.Migrations
{
    [DbContext(typeof(EstoqueContext))]
    partial class EstoqueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Inativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Superior")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("UsuarioCadastro");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Estoque", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Inativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Superior")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.HistoricoValorItem", b =>
                {
                    b.Property<int?>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoProduto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicial")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Codigo");

                    b.ToTable("HistoricoValorItens");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoUnidade")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Inativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeMinima")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCategoria");

                    b.HasIndex("CodigoUnidade");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.ItemEstoque", b =>
                {
                    b.Property<int>("CodigoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("CodigoEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstoqueCodigo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("CodigoItem", "CodigoEstoque");

                    b.HasIndex("CodigoEstoque");

                    b.HasIndex("EstoqueCodigo");

                    b.ToTable("ItensEstoque");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.ItemMovimentacao", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoMovimentacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoMovimentacao");

                    b.ToTable("ItensMovimentacao");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.KardexDiario", b =>
                {
                    b.Property<int?>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoEstoqueDestino")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoEstoqueOrigem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoItem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoMovimentacao")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeEstoqueDestinoFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeEstoqueDestinoInicial")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeEstoqueOrigemFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeEstoqueOrigemInicial")
                        .HasColumnType("INTEGER");

                    b.HasKey("Codigo");

                    b.ToTable("KardexDiario");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Movimentacao", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoEstoqueSolicitado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoEstoqueSolicitante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoTipoMovimentacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoUsuarioEstoqueSolicitado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoUsuarioEstoqueSolicitante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Novo");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoTipoMovimentacao");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.TipoMovimentacao", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Inativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("TiposMovimentacoes");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Unidade", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Inativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioCadastro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1a2b3c4d-5e6f-7g8h-9i0j-k1l2m3n4o5p6",
                            Name = "GerenteDeEstoque",
                            NormalizedName = "GERENTEDEESTOQUE"
                        },
                        new
                        {
                            Id = "2b3c4d5e-6f7g-8h9i-0j1k-l2m3n4o5p6q",
                            Name = "Almoxarife",
                            NormalizedName = "ALMOXARIFE"
                        },
                        new
                        {
                            Id = "3c4d5e6f-7g8h-9i0j-k1l2-m3n4o5p6q7r",
                            Name = "GestorDeCompras",
                            NormalizedName = "GESTORDECOMPRAS"
                        },
                        new
                        {
                            Id = "4d5e6f7g-8h9i-0j1k-l2m3-n4o5p6q7r8s",
                            Name = "GestorDeVendas",
                            NormalizedName = "GESTORDEVENDAS"
                        },
                        new
                        {
                            Id = "5e6f7g8h-9i0j-k1l2-m3n4-o5p6q7r8s9t",
                            Name = "GestorDeInventario",
                            NormalizedName = "GESTORDEINVENTARIO"
                        },
                        new
                        {
                            Id = "6f7g8h9i-0j1k-l2m3-n4o5-p6q7r8s9t0u",
                            Name = "GerenteDeLogistica",
                            NormalizedName = "GERENTEDELOGISTICA"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UsuarioCadastro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Item", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CodigoCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("CodigoUnidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.ItemEstoque", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Estoque", "Estoque")
                        .WithMany()
                        .HasForeignKey("CodigoEstoque")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("CodigoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Estoque", null)
                        .WithMany("ItensEstoque")
                        .HasForeignKey("EstoqueCodigo");

                    b.Navigation("Estoque");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.ItemMovimentacao", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Movimentacao", "Movimentacao")
                        .WithMany("ItensMovimentacao")
                        .HasForeignKey("CodigoMovimentacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Movimentacao", b =>
                {
                    b.HasOne("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.TipoMovimentacao", "TipoMovimentacao")
                        .WithMany()
                        .HasForeignKey("CodigoTipoMovimentacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoMovimentacao");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Estoque", b =>
                {
                    b.Navigation("ItensEstoque");
                });

            modelBuilder.Entity("ApiSistemaEstoque.ApiSistemaEstoque.Domain.Entities.Movimentacao", b =>
                {
                    b.Navigation("ItensMovimentacao");
                });
#pragma warning restore 612, 618
        }
    }
}
